--Generated By msgid-gen-lua Do not Edit
local config = {
	[10000] = (require("Net.Protol.common_pb")).test4,
	[10001] = (require("Net.Protol.common_pb")).test3,
	[10002] = (require("Net.Protol.common_pb")).client_info,
	[10003] = (require("Net.Protol.common_pb")).match_player,
	[20000] = (require("Net.Protol.login_pb")).test2,
	[20001] = (require("Net.Protol.login_pb")).test1,
	[20002] = (require("Net.Protol.login_pb")).req_login,
	[20003] = (require("Net.Protol.login_pb")).rsp_login,
	[20004] = (require("Net.Protol.login_pb")).ntf_logout,
	[20010] = (require("Net.Protol.user_pb")).req_create_user,
	[20011] = (require("Net.Protol.user_pb")).rsp_create_user,
	[20012] = (require("Net.Protol.user_pb")).req_change_name,
	[20013] = (require("Net.Protol.user_pb")).rsp_change_name,
	[20020] = (require("Net.Protol.room_pb")).req_join_match,
	[20021] = (require("Net.Protol.room_pb")).rsp_join_match,
	[20022] = (require("Net.Protol.room_pb")).ntf_join_match_mateinfo,
	[20023] = (require("Net.Protol.room_pb")).ntf_join_match_result,
	[20024] = (require("Net.Protol.room_pb")).req_cancel_join_match,
	[20025] = (require("Net.Protol.room_pb")).rsp_cancel_join_match,
}
return config
