// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package Net.Protol.user;

public final class User {
  private User() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface req_create_userOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string name = 2 [default = ""];
    /**
     * <code>optional string name = 2 [default = ""];</code>
     *
     * <pre>
     *optional int32 sex = 1[default = 0];	            //0是男，1是女
     * </pre>
     */
    boolean hasName();
    /**
     * <code>optional string name = 2 [default = ""];</code>
     *
     * <pre>
     *optional int32 sex = 1[default = 0];	            //0是男，1是女
     * </pre>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 2 [default = ""];</code>
     *
     * <pre>
     *optional int32 sex = 1[default = 0];	            //0是男，1是女
     * </pre>
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code Net.Protol.user.req_create_user}
   */
  public static final class req_create_user extends
      com.google.protobuf.GeneratedMessage
      implements req_create_userOrBuilder {
    // Use req_create_user.newBuilder() to construct.
    private req_create_user(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private req_create_user(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final req_create_user defaultInstance;
    public static req_create_user getDefaultInstance() {
      return defaultInstance;
    }

    public req_create_user getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private req_create_user(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000001;
              name_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Net.Protol.user.User.internal_static_Net_Protol_user_req_create_user_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Net.Protol.user.User.internal_static_Net_Protol_user_req_create_user_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Net.Protol.user.User.req_create_user.class, Net.Protol.user.User.req_create_user.Builder.class);
    }

    public static com.google.protobuf.Parser<req_create_user> PARSER =
        new com.google.protobuf.AbstractParser<req_create_user>() {
      public req_create_user parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new req_create_user(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<req_create_user> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string name = 2 [default = ""];
    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.Object name_;
    /**
     * <code>optional string name = 2 [default = ""];</code>
     *
     * <pre>
     *optional int32 sex = 1[default = 0];	            //0是男，1是女
     * </pre>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string name = 2 [default = ""];</code>
     *
     * <pre>
     *optional int32 sex = 1[default = 0];	            //0是男，1是女
     * </pre>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 2 [default = ""];</code>
     *
     * <pre>
     *optional int32 sex = 1[default = 0];	            //0是男，1是女
     * </pre>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      name_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(2, getNameBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Net.Protol.user.User.req_create_user parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Net.Protol.user.User.req_create_user parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Net.Protol.user.User.req_create_user parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Net.Protol.user.User.req_create_user parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Net.Protol.user.User.req_create_user parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Net.Protol.user.User.req_create_user parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Net.Protol.user.User.req_create_user parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Net.Protol.user.User.req_create_user parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Net.Protol.user.User.req_create_user parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Net.Protol.user.User.req_create_user parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Net.Protol.user.User.req_create_user prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Net.Protol.user.req_create_user}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements Net.Protol.user.User.req_create_userOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Net.Protol.user.User.internal_static_Net_Protol_user_req_create_user_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Net.Protol.user.User.internal_static_Net_Protol_user_req_create_user_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Net.Protol.user.User.req_create_user.class, Net.Protol.user.User.req_create_user.Builder.class);
      }

      // Construct using Net.Protol.user.User.req_create_user.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Net.Protol.user.User.internal_static_Net_Protol_user_req_create_user_descriptor;
      }

      public Net.Protol.user.User.req_create_user getDefaultInstanceForType() {
        return Net.Protol.user.User.req_create_user.getDefaultInstance();
      }

      public Net.Protol.user.User.req_create_user build() {
        Net.Protol.user.User.req_create_user result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Net.Protol.user.User.req_create_user buildPartial() {
        Net.Protol.user.User.req_create_user result = new Net.Protol.user.User.req_create_user(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Net.Protol.user.User.req_create_user) {
          return mergeFrom((Net.Protol.user.User.req_create_user)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Net.Protol.user.User.req_create_user other) {
        if (other == Net.Protol.user.User.req_create_user.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Net.Protol.user.User.req_create_user parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Net.Protol.user.User.req_create_user) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string name = 2 [default = ""];
      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 2 [default = ""];</code>
       *
       * <pre>
       *optional int32 sex = 1[default = 0];	            //0是男，1是女
       * </pre>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string name = 2 [default = ""];</code>
       *
       * <pre>
       *optional int32 sex = 1[default = 0];	            //0是男，1是女
       * </pre>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 2 [default = ""];</code>
       *
       * <pre>
       *optional int32 sex = 1[default = 0];	            //0是男，1是女
       * </pre>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 2 [default = ""];</code>
       *
       * <pre>
       *optional int32 sex = 1[default = 0];	            //0是男，1是女
       * </pre>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2 [default = ""];</code>
       *
       * <pre>
       *optional int32 sex = 1[default = 0];	            //0是男，1是女
       * </pre>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2 [default = ""];</code>
       *
       * <pre>
       *optional int32 sex = 1[default = 0];	            //0是男，1是女
       * </pre>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Net.Protol.user.req_create_user)
    }

    static {
      defaultInstance = new req_create_user(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Net.Protol.user.req_create_user)
  }

  public interface rsp_create_userOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 result = 1 [default = 0];
    /**
     * <code>optional int32 result = 1 [default = 0];</code>
     *
     * <pre>
     *0成功，-1是名字有敏感词，-2是名字已经存在
     * </pre>
     */
    boolean hasResult();
    /**
     * <code>optional int32 result = 1 [default = 0];</code>
     *
     * <pre>
     *0成功，-1是名字有敏感词，-2是名字已经存在
     * </pre>
     */
    int getResult();

    // optional string name = 3 [default = ""];
    /**
     * <code>optional string name = 3 [default = ""];</code>
     *
     * <pre>
     *optional int32 sex = 2[default = 0];	           //0是男，1是女
     * </pre>
     */
    boolean hasName();
    /**
     * <code>optional string name = 3 [default = ""];</code>
     *
     * <pre>
     *optional int32 sex = 2[default = 0];	           //0是男，1是女
     * </pre>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 3 [default = ""];</code>
     *
     * <pre>
     *optional int32 sex = 2[default = 0];	           //0是男，1是女
     * </pre>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    // optional int32 use_icon = 4 [default = 0];
    /**
     * <code>optional int32 use_icon = 4 [default = 0];</code>
     */
    boolean hasUseIcon();
    /**
     * <code>optional int32 use_icon = 4 [default = 0];</code>
     */
    int getUseIcon();
  }
  /**
   * Protobuf type {@code Net.Protol.user.rsp_create_user}
   */
  public static final class rsp_create_user extends
      com.google.protobuf.GeneratedMessage
      implements rsp_create_userOrBuilder {
    // Use rsp_create_user.newBuilder() to construct.
    private rsp_create_user(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private rsp_create_user(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final rsp_create_user defaultInstance;
    public static rsp_create_user getDefaultInstance() {
      return defaultInstance;
    }

    public rsp_create_user getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private rsp_create_user(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              result_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000002;
              name_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000004;
              useIcon_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Net.Protol.user.User.internal_static_Net_Protol_user_rsp_create_user_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Net.Protol.user.User.internal_static_Net_Protol_user_rsp_create_user_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Net.Protol.user.User.rsp_create_user.class, Net.Protol.user.User.rsp_create_user.Builder.class);
    }

    public static com.google.protobuf.Parser<rsp_create_user> PARSER =
        new com.google.protobuf.AbstractParser<rsp_create_user>() {
      public rsp_create_user parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new rsp_create_user(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<rsp_create_user> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 result = 1 [default = 0];
    public static final int RESULT_FIELD_NUMBER = 1;
    private int result_;
    /**
     * <code>optional int32 result = 1 [default = 0];</code>
     *
     * <pre>
     *0成功，-1是名字有敏感词，-2是名字已经存在
     * </pre>
     */
    public boolean hasResult() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 result = 1 [default = 0];</code>
     *
     * <pre>
     *0成功，-1是名字有敏感词，-2是名字已经存在
     * </pre>
     */
    public int getResult() {
      return result_;
    }

    // optional string name = 3 [default = ""];
    public static final int NAME_FIELD_NUMBER = 3;
    private java.lang.Object name_;
    /**
     * <code>optional string name = 3 [default = ""];</code>
     *
     * <pre>
     *optional int32 sex = 2[default = 0];	           //0是男，1是女
     * </pre>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string name = 3 [default = ""];</code>
     *
     * <pre>
     *optional int32 sex = 2[default = 0];	           //0是男，1是女
     * </pre>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 3 [default = ""];</code>
     *
     * <pre>
     *optional int32 sex = 2[default = 0];	           //0是男，1是女
     * </pre>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 use_icon = 4 [default = 0];
    public static final int USE_ICON_FIELD_NUMBER = 4;
    private int useIcon_;
    /**
     * <code>optional int32 use_icon = 4 [default = 0];</code>
     */
    public boolean hasUseIcon() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 use_icon = 4 [default = 0];</code>
     */
    public int getUseIcon() {
      return useIcon_;
    }

    private void initFields() {
      result_ = 0;
      name_ = "";
      useIcon_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, result_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(3, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(4, useIcon_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, result_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, useIcon_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Net.Protol.user.User.rsp_create_user parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Net.Protol.user.User.rsp_create_user parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Net.Protol.user.User.rsp_create_user parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Net.Protol.user.User.rsp_create_user parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Net.Protol.user.User.rsp_create_user parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Net.Protol.user.User.rsp_create_user parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Net.Protol.user.User.rsp_create_user parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Net.Protol.user.User.rsp_create_user parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Net.Protol.user.User.rsp_create_user parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Net.Protol.user.User.rsp_create_user parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Net.Protol.user.User.rsp_create_user prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Net.Protol.user.rsp_create_user}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements Net.Protol.user.User.rsp_create_userOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Net.Protol.user.User.internal_static_Net_Protol_user_rsp_create_user_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Net.Protol.user.User.internal_static_Net_Protol_user_rsp_create_user_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Net.Protol.user.User.rsp_create_user.class, Net.Protol.user.User.rsp_create_user.Builder.class);
      }

      // Construct using Net.Protol.user.User.rsp_create_user.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        result_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        useIcon_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Net.Protol.user.User.internal_static_Net_Protol_user_rsp_create_user_descriptor;
      }

      public Net.Protol.user.User.rsp_create_user getDefaultInstanceForType() {
        return Net.Protol.user.User.rsp_create_user.getDefaultInstance();
      }

      public Net.Protol.user.User.rsp_create_user build() {
        Net.Protol.user.User.rsp_create_user result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Net.Protol.user.User.rsp_create_user buildPartial() {
        Net.Protol.user.User.rsp_create_user result = new Net.Protol.user.User.rsp_create_user(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.result_ = result_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.useIcon_ = useIcon_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Net.Protol.user.User.rsp_create_user) {
          return mergeFrom((Net.Protol.user.User.rsp_create_user)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Net.Protol.user.User.rsp_create_user other) {
        if (other == Net.Protol.user.User.rsp_create_user.getDefaultInstance()) return this;
        if (other.hasResult()) {
          setResult(other.getResult());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasUseIcon()) {
          setUseIcon(other.getUseIcon());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Net.Protol.user.User.rsp_create_user parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Net.Protol.user.User.rsp_create_user) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 result = 1 [default = 0];
      private int result_ ;
      /**
       * <code>optional int32 result = 1 [default = 0];</code>
       *
       * <pre>
       *0成功，-1是名字有敏感词，-2是名字已经存在
       * </pre>
       */
      public boolean hasResult() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 result = 1 [default = 0];</code>
       *
       * <pre>
       *0成功，-1是名字有敏感词，-2是名字已经存在
       * </pre>
       */
      public int getResult() {
        return result_;
      }
      /**
       * <code>optional int32 result = 1 [default = 0];</code>
       *
       * <pre>
       *0成功，-1是名字有敏感词，-2是名字已经存在
       * </pre>
       */
      public Builder setResult(int value) {
        bitField0_ |= 0x00000001;
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 result = 1 [default = 0];</code>
       *
       * <pre>
       *0成功，-1是名字有敏感词，-2是名字已经存在
       * </pre>
       */
      public Builder clearResult() {
        bitField0_ = (bitField0_ & ~0x00000001);
        result_ = 0;
        onChanged();
        return this;
      }

      // optional string name = 3 [default = ""];
      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 3 [default = ""];</code>
       *
       * <pre>
       *optional int32 sex = 2[default = 0];	           //0是男，1是女
       * </pre>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string name = 3 [default = ""];</code>
       *
       * <pre>
       *optional int32 sex = 2[default = 0];	           //0是男，1是女
       * </pre>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 3 [default = ""];</code>
       *
       * <pre>
       *optional int32 sex = 2[default = 0];	           //0是男，1是女
       * </pre>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 3 [default = ""];</code>
       *
       * <pre>
       *optional int32 sex = 2[default = 0];	           //0是男，1是女
       * </pre>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 3 [default = ""];</code>
       *
       * <pre>
       *optional int32 sex = 2[default = 0];	           //0是男，1是女
       * </pre>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 3 [default = ""];</code>
       *
       * <pre>
       *optional int32 sex = 2[default = 0];	           //0是男，1是女
       * </pre>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }

      // optional int32 use_icon = 4 [default = 0];
      private int useIcon_ ;
      /**
       * <code>optional int32 use_icon = 4 [default = 0];</code>
       */
      public boolean hasUseIcon() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 use_icon = 4 [default = 0];</code>
       */
      public int getUseIcon() {
        return useIcon_;
      }
      /**
       * <code>optional int32 use_icon = 4 [default = 0];</code>
       */
      public Builder setUseIcon(int value) {
        bitField0_ |= 0x00000004;
        useIcon_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 use_icon = 4 [default = 0];</code>
       */
      public Builder clearUseIcon() {
        bitField0_ = (bitField0_ & ~0x00000004);
        useIcon_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Net.Protol.user.rsp_create_user)
    }

    static {
      defaultInstance = new rsp_create_user(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Net.Protol.user.rsp_create_user)
  }

  public interface req_change_nameOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string name = 1 [default = ""];
    /**
     * <code>optional string name = 1 [default = ""];</code>
     */
    boolean hasName();
    /**
     * <code>optional string name = 1 [default = ""];</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 1 [default = ""];</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code Net.Protol.user.req_change_name}
   */
  public static final class req_change_name extends
      com.google.protobuf.GeneratedMessage
      implements req_change_nameOrBuilder {
    // Use req_change_name.newBuilder() to construct.
    private req_change_name(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private req_change_name(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final req_change_name defaultInstance;
    public static req_change_name getDefaultInstance() {
      return defaultInstance;
    }

    public req_change_name getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private req_change_name(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              name_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Net.Protol.user.User.internal_static_Net_Protol_user_req_change_name_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Net.Protol.user.User.internal_static_Net_Protol_user_req_change_name_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Net.Protol.user.User.req_change_name.class, Net.Protol.user.User.req_change_name.Builder.class);
    }

    public static com.google.protobuf.Parser<req_change_name> PARSER =
        new com.google.protobuf.AbstractParser<req_change_name>() {
      public req_change_name parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new req_change_name(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<req_change_name> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string name = 1 [default = ""];
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    /**
     * <code>optional string name = 1 [default = ""];</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string name = 1 [default = ""];</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 1 [default = ""];</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      name_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Net.Protol.user.User.req_change_name parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Net.Protol.user.User.req_change_name parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Net.Protol.user.User.req_change_name parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Net.Protol.user.User.req_change_name parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Net.Protol.user.User.req_change_name parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Net.Protol.user.User.req_change_name parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Net.Protol.user.User.req_change_name parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Net.Protol.user.User.req_change_name parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Net.Protol.user.User.req_change_name parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Net.Protol.user.User.req_change_name parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Net.Protol.user.User.req_change_name prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Net.Protol.user.req_change_name}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements Net.Protol.user.User.req_change_nameOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Net.Protol.user.User.internal_static_Net_Protol_user_req_change_name_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Net.Protol.user.User.internal_static_Net_Protol_user_req_change_name_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Net.Protol.user.User.req_change_name.class, Net.Protol.user.User.req_change_name.Builder.class);
      }

      // Construct using Net.Protol.user.User.req_change_name.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Net.Protol.user.User.internal_static_Net_Protol_user_req_change_name_descriptor;
      }

      public Net.Protol.user.User.req_change_name getDefaultInstanceForType() {
        return Net.Protol.user.User.req_change_name.getDefaultInstance();
      }

      public Net.Protol.user.User.req_change_name build() {
        Net.Protol.user.User.req_change_name result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Net.Protol.user.User.req_change_name buildPartial() {
        Net.Protol.user.User.req_change_name result = new Net.Protol.user.User.req_change_name(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Net.Protol.user.User.req_change_name) {
          return mergeFrom((Net.Protol.user.User.req_change_name)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Net.Protol.user.User.req_change_name other) {
        if (other == Net.Protol.user.User.req_change_name.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Net.Protol.user.User.req_change_name parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Net.Protol.user.User.req_change_name) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string name = 1 [default = ""];
      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 1 [default = ""];</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string name = 1 [default = ""];</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 1 [default = ""];</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 1 [default = ""];</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1 [default = ""];</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1 [default = ""];</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Net.Protol.user.req_change_name)
    }

    static {
      defaultInstance = new req_change_name(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Net.Protol.user.req_change_name)
  }

  public interface rsp_change_nameOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 result = 1 [default = 0];
    /**
     * <code>optional int32 result = 1 [default = 0];</code>
     */
    boolean hasResult();
    /**
     * <code>optional int32 result = 1 [default = 0];</code>
     */
    int getResult();

    // optional string name = 2 [default = ""];
    /**
     * <code>optional string name = 2 [default = ""];</code>
     */
    boolean hasName();
    /**
     * <code>optional string name = 2 [default = ""];</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 2 [default = ""];</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code Net.Protol.user.rsp_change_name}
   */
  public static final class rsp_change_name extends
      com.google.protobuf.GeneratedMessage
      implements rsp_change_nameOrBuilder {
    // Use rsp_change_name.newBuilder() to construct.
    private rsp_change_name(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private rsp_change_name(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final rsp_change_name defaultInstance;
    public static rsp_change_name getDefaultInstance() {
      return defaultInstance;
    }

    public rsp_change_name getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private rsp_change_name(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              result_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              name_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Net.Protol.user.User.internal_static_Net_Protol_user_rsp_change_name_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Net.Protol.user.User.internal_static_Net_Protol_user_rsp_change_name_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Net.Protol.user.User.rsp_change_name.class, Net.Protol.user.User.rsp_change_name.Builder.class);
    }

    public static com.google.protobuf.Parser<rsp_change_name> PARSER =
        new com.google.protobuf.AbstractParser<rsp_change_name>() {
      public rsp_change_name parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new rsp_change_name(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<rsp_change_name> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 result = 1 [default = 0];
    public static final int RESULT_FIELD_NUMBER = 1;
    private int result_;
    /**
     * <code>optional int32 result = 1 [default = 0];</code>
     */
    public boolean hasResult() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 result = 1 [default = 0];</code>
     */
    public int getResult() {
      return result_;
    }

    // optional string name = 2 [default = ""];
    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.Object name_;
    /**
     * <code>optional string name = 2 [default = ""];</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string name = 2 [default = ""];</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 2 [default = ""];</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      result_ = 0;
      name_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, result_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, result_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Net.Protol.user.User.rsp_change_name parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Net.Protol.user.User.rsp_change_name parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Net.Protol.user.User.rsp_change_name parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Net.Protol.user.User.rsp_change_name parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Net.Protol.user.User.rsp_change_name parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Net.Protol.user.User.rsp_change_name parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Net.Protol.user.User.rsp_change_name parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Net.Protol.user.User.rsp_change_name parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Net.Protol.user.User.rsp_change_name parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Net.Protol.user.User.rsp_change_name parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Net.Protol.user.User.rsp_change_name prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Net.Protol.user.rsp_change_name}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements Net.Protol.user.User.rsp_change_nameOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Net.Protol.user.User.internal_static_Net_Protol_user_rsp_change_name_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Net.Protol.user.User.internal_static_Net_Protol_user_rsp_change_name_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Net.Protol.user.User.rsp_change_name.class, Net.Protol.user.User.rsp_change_name.Builder.class);
      }

      // Construct using Net.Protol.user.User.rsp_change_name.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        result_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Net.Protol.user.User.internal_static_Net_Protol_user_rsp_change_name_descriptor;
      }

      public Net.Protol.user.User.rsp_change_name getDefaultInstanceForType() {
        return Net.Protol.user.User.rsp_change_name.getDefaultInstance();
      }

      public Net.Protol.user.User.rsp_change_name build() {
        Net.Protol.user.User.rsp_change_name result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Net.Protol.user.User.rsp_change_name buildPartial() {
        Net.Protol.user.User.rsp_change_name result = new Net.Protol.user.User.rsp_change_name(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.result_ = result_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Net.Protol.user.User.rsp_change_name) {
          return mergeFrom((Net.Protol.user.User.rsp_change_name)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Net.Protol.user.User.rsp_change_name other) {
        if (other == Net.Protol.user.User.rsp_change_name.getDefaultInstance()) return this;
        if (other.hasResult()) {
          setResult(other.getResult());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Net.Protol.user.User.rsp_change_name parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Net.Protol.user.User.rsp_change_name) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 result = 1 [default = 0];
      private int result_ ;
      /**
       * <code>optional int32 result = 1 [default = 0];</code>
       */
      public boolean hasResult() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 result = 1 [default = 0];</code>
       */
      public int getResult() {
        return result_;
      }
      /**
       * <code>optional int32 result = 1 [default = 0];</code>
       */
      public Builder setResult(int value) {
        bitField0_ |= 0x00000001;
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 result = 1 [default = 0];</code>
       */
      public Builder clearResult() {
        bitField0_ = (bitField0_ & ~0x00000001);
        result_ = 0;
        onChanged();
        return this;
      }

      // optional string name = 2 [default = ""];
      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 2 [default = ""];</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string name = 2 [default = ""];</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 2 [default = ""];</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 2 [default = ""];</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2 [default = ""];</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2 [default = ""];</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Net.Protol.user.rsp_change_name)
    }

    static {
      defaultInstance = new rsp_change_name(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Net.Protol.user.rsp_change_name)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Net_Protol_user_req_create_user_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Net_Protol_user_req_create_user_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Net_Protol_user_rsp_create_user_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Net_Protol_user_rsp_create_user_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Net_Protol_user_req_change_name_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Net_Protol_user_req_change_name_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Net_Protol_user_rsp_change_name_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Net_Protol_user_rsp_change_name_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nuser.proto\022\017Net.Protol.user\"!\n\017req_cre" +
      "ate_user\022\016\n\004name\030\002 \001(\t:\000\"I\n\017rsp_create_u" +
      "ser\022\021\n\006result\030\001 \001(\005:\0010\022\016\n\004name\030\003 \001(\t:\000\022\023" +
      "\n\010use_icon\030\004 \001(\005:\0010\"!\n\017req_change_name\022\016" +
      "\n\004name\030\001 \001(\t:\000\"4\n\017rsp_change_name\022\021\n\006res" +
      "ult\030\001 \001(\005:\0010\022\016\n\004name\030\002 \001(\t:\000"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Net_Protol_user_req_create_user_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Net_Protol_user_req_create_user_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Net_Protol_user_req_create_user_descriptor,
              new java.lang.String[] { "Name", });
          internal_static_Net_Protol_user_rsp_create_user_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_Net_Protol_user_rsp_create_user_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Net_Protol_user_rsp_create_user_descriptor,
              new java.lang.String[] { "Result", "Name", "UseIcon", });
          internal_static_Net_Protol_user_req_change_name_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_Net_Protol_user_req_change_name_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Net_Protol_user_req_change_name_descriptor,
              new java.lang.String[] { "Name", });
          internal_static_Net_Protol_user_rsp_change_name_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_Net_Protol_user_rsp_change_name_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Net_Protol_user_rsp_change_name_descriptor,
              new java.lang.String[] { "Result", "Name", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
