// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package Net.Protol.common;

public final class Common {
  private Common() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface test4OrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 f = 1 [default = 0];
    /**
     * <code>optional int32 f = 1 [default = 0];</code>
     */
    boolean hasF();
    /**
     * <code>optional int32 f = 1 [default = 0];</code>
     */
    int getF();

    // optional string ccc = 2 [default = "asdasdasd"];
    /**
     * <code>optional string ccc = 2 [default = "asdasdasd"];</code>
     */
    boolean hasCcc();
    /**
     * <code>optional string ccc = 2 [default = "asdasdasd"];</code>
     */
    java.lang.String getCcc();
    /**
     * <code>optional string ccc = 2 [default = "asdasdasd"];</code>
     */
    com.google.protobuf.ByteString
        getCccBytes();

    // optional string cmd_data = 3 [default = ""];
    /**
     * <code>optional string cmd_data = 3 [default = ""];</code>
     */
    boolean hasCmdData();
    /**
     * <code>optional string cmd_data = 3 [default = ""];</code>
     */
    java.lang.String getCmdData();
    /**
     * <code>optional string cmd_data = 3 [default = ""];</code>
     */
    com.google.protobuf.ByteString
        getCmdDataBytes();
  }
  /**
   * Protobuf type {@code Net.Protol.common.test4}
   */
  public static final class test4 extends
      com.google.protobuf.GeneratedMessage
      implements test4OrBuilder {
    // Use test4.newBuilder() to construct.
    private test4(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private test4(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final test4 defaultInstance;
    public static test4 getDefaultInstance() {
      return defaultInstance;
    }

    public test4 getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private test4(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              f_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              ccc_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              cmdData_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Net.Protol.common.Common.internal_static_Net_Protol_common_test4_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Net.Protol.common.Common.internal_static_Net_Protol_common_test4_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Net.Protol.common.Common.test4.class, Net.Protol.common.Common.test4.Builder.class);
    }

    public static com.google.protobuf.Parser<test4> PARSER =
        new com.google.protobuf.AbstractParser<test4>() {
      public test4 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new test4(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<test4> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 f = 1 [default = 0];
    public static final int F_FIELD_NUMBER = 1;
    private int f_;
    /**
     * <code>optional int32 f = 1 [default = 0];</code>
     */
    public boolean hasF() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 f = 1 [default = 0];</code>
     */
    public int getF() {
      return f_;
    }

    // optional string ccc = 2 [default = "asdasdasd"];
    public static final int CCC_FIELD_NUMBER = 2;
    private java.lang.Object ccc_;
    /**
     * <code>optional string ccc = 2 [default = "asdasdasd"];</code>
     */
    public boolean hasCcc() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string ccc = 2 [default = "asdasdasd"];</code>
     */
    public java.lang.String getCcc() {
      java.lang.Object ref = ccc_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          ccc_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string ccc = 2 [default = "asdasdasd"];</code>
     */
    public com.google.protobuf.ByteString
        getCccBytes() {
      java.lang.Object ref = ccc_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ccc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string cmd_data = 3 [default = ""];
    public static final int CMD_DATA_FIELD_NUMBER = 3;
    private java.lang.Object cmdData_;
    /**
     * <code>optional string cmd_data = 3 [default = ""];</code>
     */
    public boolean hasCmdData() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string cmd_data = 3 [default = ""];</code>
     */
    public java.lang.String getCmdData() {
      java.lang.Object ref = cmdData_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          cmdData_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string cmd_data = 3 [default = ""];</code>
     */
    public com.google.protobuf.ByteString
        getCmdDataBytes() {
      java.lang.Object ref = cmdData_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cmdData_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      f_ = 0;
      ccc_ = "asdasdasd";
      cmdData_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, f_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getCccBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getCmdDataBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, f_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getCccBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getCmdDataBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Net.Protol.common.Common.test4 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Net.Protol.common.Common.test4 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Net.Protol.common.Common.test4 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Net.Protol.common.Common.test4 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Net.Protol.common.Common.test4 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Net.Protol.common.Common.test4 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Net.Protol.common.Common.test4 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Net.Protol.common.Common.test4 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Net.Protol.common.Common.test4 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Net.Protol.common.Common.test4 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Net.Protol.common.Common.test4 prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Net.Protol.common.test4}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements Net.Protol.common.Common.test4OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Net.Protol.common.Common.internal_static_Net_Protol_common_test4_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Net.Protol.common.Common.internal_static_Net_Protol_common_test4_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Net.Protol.common.Common.test4.class, Net.Protol.common.Common.test4.Builder.class);
      }

      // Construct using Net.Protol.common.Common.test4.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        f_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        ccc_ = "asdasdasd";
        bitField0_ = (bitField0_ & ~0x00000002);
        cmdData_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Net.Protol.common.Common.internal_static_Net_Protol_common_test4_descriptor;
      }

      public Net.Protol.common.Common.test4 getDefaultInstanceForType() {
        return Net.Protol.common.Common.test4.getDefaultInstance();
      }

      public Net.Protol.common.Common.test4 build() {
        Net.Protol.common.Common.test4 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Net.Protol.common.Common.test4 buildPartial() {
        Net.Protol.common.Common.test4 result = new Net.Protol.common.Common.test4(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.f_ = f_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.ccc_ = ccc_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.cmdData_ = cmdData_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Net.Protol.common.Common.test4) {
          return mergeFrom((Net.Protol.common.Common.test4)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Net.Protol.common.Common.test4 other) {
        if (other == Net.Protol.common.Common.test4.getDefaultInstance()) return this;
        if (other.hasF()) {
          setF(other.getF());
        }
        if (other.hasCcc()) {
          bitField0_ |= 0x00000002;
          ccc_ = other.ccc_;
          onChanged();
        }
        if (other.hasCmdData()) {
          bitField0_ |= 0x00000004;
          cmdData_ = other.cmdData_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Net.Protol.common.Common.test4 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Net.Protol.common.Common.test4) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 f = 1 [default = 0];
      private int f_ ;
      /**
       * <code>optional int32 f = 1 [default = 0];</code>
       */
      public boolean hasF() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 f = 1 [default = 0];</code>
       */
      public int getF() {
        return f_;
      }
      /**
       * <code>optional int32 f = 1 [default = 0];</code>
       */
      public Builder setF(int value) {
        bitField0_ |= 0x00000001;
        f_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 f = 1 [default = 0];</code>
       */
      public Builder clearF() {
        bitField0_ = (bitField0_ & ~0x00000001);
        f_ = 0;
        onChanged();
        return this;
      }

      // optional string ccc = 2 [default = "asdasdasd"];
      private java.lang.Object ccc_ = "asdasdasd";
      /**
       * <code>optional string ccc = 2 [default = "asdasdasd"];</code>
       */
      public boolean hasCcc() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string ccc = 2 [default = "asdasdasd"];</code>
       */
      public java.lang.String getCcc() {
        java.lang.Object ref = ccc_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          ccc_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string ccc = 2 [default = "asdasdasd"];</code>
       */
      public com.google.protobuf.ByteString
          getCccBytes() {
        java.lang.Object ref = ccc_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ccc_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string ccc = 2 [default = "asdasdasd"];</code>
       */
      public Builder setCcc(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        ccc_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string ccc = 2 [default = "asdasdasd"];</code>
       */
      public Builder clearCcc() {
        bitField0_ = (bitField0_ & ~0x00000002);
        ccc_ = getDefaultInstance().getCcc();
        onChanged();
        return this;
      }
      /**
       * <code>optional string ccc = 2 [default = "asdasdasd"];</code>
       */
      public Builder setCccBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        ccc_ = value;
        onChanged();
        return this;
      }

      // optional string cmd_data = 3 [default = ""];
      private java.lang.Object cmdData_ = "";
      /**
       * <code>optional string cmd_data = 3 [default = ""];</code>
       */
      public boolean hasCmdData() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string cmd_data = 3 [default = ""];</code>
       */
      public java.lang.String getCmdData() {
        java.lang.Object ref = cmdData_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          cmdData_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string cmd_data = 3 [default = ""];</code>
       */
      public com.google.protobuf.ByteString
          getCmdDataBytes() {
        java.lang.Object ref = cmdData_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cmdData_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string cmd_data = 3 [default = ""];</code>
       */
      public Builder setCmdData(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        cmdData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string cmd_data = 3 [default = ""];</code>
       */
      public Builder clearCmdData() {
        bitField0_ = (bitField0_ & ~0x00000004);
        cmdData_ = getDefaultInstance().getCmdData();
        onChanged();
        return this;
      }
      /**
       * <code>optional string cmd_data = 3 [default = ""];</code>
       */
      public Builder setCmdDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        cmdData_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Net.Protol.common.test4)
    }

    static {
      defaultInstance = new test4(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Net.Protol.common.test4)
  }

  public interface test3OrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 d = 1 [default = 0];
    /**
     * <code>optional int32 d = 1 [default = 0];</code>
     */
    boolean hasD();
    /**
     * <code>optional int32 d = 1 [default = 0];</code>
     */
    int getD();

    // optional .Net.Protol.common.test4 cc = 2;
    /**
     * <code>optional .Net.Protol.common.test4 cc = 2;</code>
     */
    boolean hasCc();
    /**
     * <code>optional .Net.Protol.common.test4 cc = 2;</code>
     */
    Net.Protol.common.Common.test4 getCc();
    /**
     * <code>optional .Net.Protol.common.test4 cc = 2;</code>
     */
    Net.Protol.common.Common.test4OrBuilder getCcOrBuilder();
  }
  /**
   * Protobuf type {@code Net.Protol.common.test3}
   */
  public static final class test3 extends
      com.google.protobuf.GeneratedMessage
      implements test3OrBuilder {
    // Use test3.newBuilder() to construct.
    private test3(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private test3(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final test3 defaultInstance;
    public static test3 getDefaultInstance() {
      return defaultInstance;
    }

    public test3 getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private test3(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              d_ = input.readInt32();
              break;
            }
            case 18: {
              Net.Protol.common.Common.test4.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = cc_.toBuilder();
              }
              cc_ = input.readMessage(Net.Protol.common.Common.test4.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(cc_);
                cc_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Net.Protol.common.Common.internal_static_Net_Protol_common_test3_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Net.Protol.common.Common.internal_static_Net_Protol_common_test3_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Net.Protol.common.Common.test3.class, Net.Protol.common.Common.test3.Builder.class);
    }

    public static com.google.protobuf.Parser<test3> PARSER =
        new com.google.protobuf.AbstractParser<test3>() {
      public test3 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new test3(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<test3> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 d = 1 [default = 0];
    public static final int D_FIELD_NUMBER = 1;
    private int d_;
    /**
     * <code>optional int32 d = 1 [default = 0];</code>
     */
    public boolean hasD() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 d = 1 [default = 0];</code>
     */
    public int getD() {
      return d_;
    }

    // optional .Net.Protol.common.test4 cc = 2;
    public static final int CC_FIELD_NUMBER = 2;
    private Net.Protol.common.Common.test4 cc_;
    /**
     * <code>optional .Net.Protol.common.test4 cc = 2;</code>
     */
    public boolean hasCc() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .Net.Protol.common.test4 cc = 2;</code>
     */
    public Net.Protol.common.Common.test4 getCc() {
      return cc_;
    }
    /**
     * <code>optional .Net.Protol.common.test4 cc = 2;</code>
     */
    public Net.Protol.common.Common.test4OrBuilder getCcOrBuilder() {
      return cc_;
    }

    private void initFields() {
      d_ = 0;
      cc_ = Net.Protol.common.Common.test4.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, d_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, cc_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, d_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, cc_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Net.Protol.common.Common.test3 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Net.Protol.common.Common.test3 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Net.Protol.common.Common.test3 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Net.Protol.common.Common.test3 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Net.Protol.common.Common.test3 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Net.Protol.common.Common.test3 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Net.Protol.common.Common.test3 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Net.Protol.common.Common.test3 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Net.Protol.common.Common.test3 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Net.Protol.common.Common.test3 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Net.Protol.common.Common.test3 prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Net.Protol.common.test3}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements Net.Protol.common.Common.test3OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Net.Protol.common.Common.internal_static_Net_Protol_common_test3_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Net.Protol.common.Common.internal_static_Net_Protol_common_test3_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Net.Protol.common.Common.test3.class, Net.Protol.common.Common.test3.Builder.class);
      }

      // Construct using Net.Protol.common.Common.test3.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getCcFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        d_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (ccBuilder_ == null) {
          cc_ = Net.Protol.common.Common.test4.getDefaultInstance();
        } else {
          ccBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Net.Protol.common.Common.internal_static_Net_Protol_common_test3_descriptor;
      }

      public Net.Protol.common.Common.test3 getDefaultInstanceForType() {
        return Net.Protol.common.Common.test3.getDefaultInstance();
      }

      public Net.Protol.common.Common.test3 build() {
        Net.Protol.common.Common.test3 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Net.Protol.common.Common.test3 buildPartial() {
        Net.Protol.common.Common.test3 result = new Net.Protol.common.Common.test3(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.d_ = d_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (ccBuilder_ == null) {
          result.cc_ = cc_;
        } else {
          result.cc_ = ccBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Net.Protol.common.Common.test3) {
          return mergeFrom((Net.Protol.common.Common.test3)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Net.Protol.common.Common.test3 other) {
        if (other == Net.Protol.common.Common.test3.getDefaultInstance()) return this;
        if (other.hasD()) {
          setD(other.getD());
        }
        if (other.hasCc()) {
          mergeCc(other.getCc());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Net.Protol.common.Common.test3 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Net.Protol.common.Common.test3) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 d = 1 [default = 0];
      private int d_ ;
      /**
       * <code>optional int32 d = 1 [default = 0];</code>
       */
      public boolean hasD() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 d = 1 [default = 0];</code>
       */
      public int getD() {
        return d_;
      }
      /**
       * <code>optional int32 d = 1 [default = 0];</code>
       */
      public Builder setD(int value) {
        bitField0_ |= 0x00000001;
        d_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 d = 1 [default = 0];</code>
       */
      public Builder clearD() {
        bitField0_ = (bitField0_ & ~0x00000001);
        d_ = 0;
        onChanged();
        return this;
      }

      // optional .Net.Protol.common.test4 cc = 2;
      private Net.Protol.common.Common.test4 cc_ = Net.Protol.common.Common.test4.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          Net.Protol.common.Common.test4, Net.Protol.common.Common.test4.Builder, Net.Protol.common.Common.test4OrBuilder> ccBuilder_;
      /**
       * <code>optional .Net.Protol.common.test4 cc = 2;</code>
       */
      public boolean hasCc() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .Net.Protol.common.test4 cc = 2;</code>
       */
      public Net.Protol.common.Common.test4 getCc() {
        if (ccBuilder_ == null) {
          return cc_;
        } else {
          return ccBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Net.Protol.common.test4 cc = 2;</code>
       */
      public Builder setCc(Net.Protol.common.Common.test4 value) {
        if (ccBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          cc_ = value;
          onChanged();
        } else {
          ccBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .Net.Protol.common.test4 cc = 2;</code>
       */
      public Builder setCc(
          Net.Protol.common.Common.test4.Builder builderForValue) {
        if (ccBuilder_ == null) {
          cc_ = builderForValue.build();
          onChanged();
        } else {
          ccBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .Net.Protol.common.test4 cc = 2;</code>
       */
      public Builder mergeCc(Net.Protol.common.Common.test4 value) {
        if (ccBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              cc_ != Net.Protol.common.Common.test4.getDefaultInstance()) {
            cc_ =
              Net.Protol.common.Common.test4.newBuilder(cc_).mergeFrom(value).buildPartial();
          } else {
            cc_ = value;
          }
          onChanged();
        } else {
          ccBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .Net.Protol.common.test4 cc = 2;</code>
       */
      public Builder clearCc() {
        if (ccBuilder_ == null) {
          cc_ = Net.Protol.common.Common.test4.getDefaultInstance();
          onChanged();
        } else {
          ccBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .Net.Protol.common.test4 cc = 2;</code>
       */
      public Net.Protol.common.Common.test4.Builder getCcBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getCcFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Net.Protol.common.test4 cc = 2;</code>
       */
      public Net.Protol.common.Common.test4OrBuilder getCcOrBuilder() {
        if (ccBuilder_ != null) {
          return ccBuilder_.getMessageOrBuilder();
        } else {
          return cc_;
        }
      }
      /**
       * <code>optional .Net.Protol.common.test4 cc = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          Net.Protol.common.Common.test4, Net.Protol.common.Common.test4.Builder, Net.Protol.common.Common.test4OrBuilder> 
          getCcFieldBuilder() {
        if (ccBuilder_ == null) {
          ccBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              Net.Protol.common.Common.test4, Net.Protol.common.Common.test4.Builder, Net.Protol.common.Common.test4OrBuilder>(
                  cc_,
                  getParentForChildren(),
                  isClean());
          cc_ = null;
        }
        return ccBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:Net.Protol.common.test3)
    }

    static {
      defaultInstance = new test3(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Net.Protol.common.test3)
  }

  public interface client_infoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string user_name = 7 [default = ""];
    /**
     * <code>optional string user_name = 7 [default = ""];</code>
     *
     * <pre>
     *用户相关///////////////////////////////
     * </pre>
     */
    boolean hasUserName();
    /**
     * <code>optional string user_name = 7 [default = ""];</code>
     *
     * <pre>
     *用户相关///////////////////////////////
     * </pre>
     */
    java.lang.String getUserName();
    /**
     * <code>optional string user_name = 7 [default = ""];</code>
     *
     * <pre>
     *用户相关///////////////////////////////
     * </pre>
     */
    com.google.protobuf.ByteString
        getUserNameBytes();

    // optional int32 use_icon = 8 [default = 0];
    /**
     * <code>optional int32 use_icon = 8 [default = 0];</code>
     *
     * <pre>
     *正在使用的头像
     * </pre>
     */
    boolean hasUseIcon();
    /**
     * <code>optional int32 use_icon = 8 [default = 0];</code>
     *
     * <pre>
     *正在使用的头像
     * </pre>
     */
    int getUseIcon();
  }
  /**
   * Protobuf type {@code Net.Protol.common.client_info}
   */
  public static final class client_info extends
      com.google.protobuf.GeneratedMessage
      implements client_infoOrBuilder {
    // Use client_info.newBuilder() to construct.
    private client_info(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private client_info(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final client_info defaultInstance;
    public static client_info getDefaultInstance() {
      return defaultInstance;
    }

    public client_info getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private client_info(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 58: {
              bitField0_ |= 0x00000001;
              userName_ = input.readBytes();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000002;
              useIcon_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Net.Protol.common.Common.internal_static_Net_Protol_common_client_info_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Net.Protol.common.Common.internal_static_Net_Protol_common_client_info_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Net.Protol.common.Common.client_info.class, Net.Protol.common.Common.client_info.Builder.class);
    }

    public static com.google.protobuf.Parser<client_info> PARSER =
        new com.google.protobuf.AbstractParser<client_info>() {
      public client_info parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new client_info(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<client_info> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string user_name = 7 [default = ""];
    public static final int USER_NAME_FIELD_NUMBER = 7;
    private java.lang.Object userName_;
    /**
     * <code>optional string user_name = 7 [default = ""];</code>
     *
     * <pre>
     *用户相关///////////////////////////////
     * </pre>
     */
    public boolean hasUserName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string user_name = 7 [default = ""];</code>
     *
     * <pre>
     *用户相关///////////////////////////////
     * </pre>
     */
    public java.lang.String getUserName() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string user_name = 7 [default = ""];</code>
     *
     * <pre>
     *用户相关///////////////////////////////
     * </pre>
     */
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 use_icon = 8 [default = 0];
    public static final int USE_ICON_FIELD_NUMBER = 8;
    private int useIcon_;
    /**
     * <code>optional int32 use_icon = 8 [default = 0];</code>
     *
     * <pre>
     *正在使用的头像
     * </pre>
     */
    public boolean hasUseIcon() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 use_icon = 8 [default = 0];</code>
     *
     * <pre>
     *正在使用的头像
     * </pre>
     */
    public int getUseIcon() {
      return useIcon_;
    }

    private void initFields() {
      userName_ = "";
      useIcon_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(7, getUserNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(8, useIcon_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getUserNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, useIcon_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Net.Protol.common.Common.client_info parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Net.Protol.common.Common.client_info parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Net.Protol.common.Common.client_info parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Net.Protol.common.Common.client_info parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Net.Protol.common.Common.client_info parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Net.Protol.common.Common.client_info parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Net.Protol.common.Common.client_info parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Net.Protol.common.Common.client_info parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Net.Protol.common.Common.client_info parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Net.Protol.common.Common.client_info parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Net.Protol.common.Common.client_info prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Net.Protol.common.client_info}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements Net.Protol.common.Common.client_infoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Net.Protol.common.Common.internal_static_Net_Protol_common_client_info_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Net.Protol.common.Common.internal_static_Net_Protol_common_client_info_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Net.Protol.common.Common.client_info.class, Net.Protol.common.Common.client_info.Builder.class);
      }

      // Construct using Net.Protol.common.Common.client_info.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        userName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        useIcon_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Net.Protol.common.Common.internal_static_Net_Protol_common_client_info_descriptor;
      }

      public Net.Protol.common.Common.client_info getDefaultInstanceForType() {
        return Net.Protol.common.Common.client_info.getDefaultInstance();
      }

      public Net.Protol.common.Common.client_info build() {
        Net.Protol.common.Common.client_info result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Net.Protol.common.Common.client_info buildPartial() {
        Net.Protol.common.Common.client_info result = new Net.Protol.common.Common.client_info(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userName_ = userName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.useIcon_ = useIcon_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Net.Protol.common.Common.client_info) {
          return mergeFrom((Net.Protol.common.Common.client_info)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Net.Protol.common.Common.client_info other) {
        if (other == Net.Protol.common.Common.client_info.getDefaultInstance()) return this;
        if (other.hasUserName()) {
          bitField0_ |= 0x00000001;
          userName_ = other.userName_;
          onChanged();
        }
        if (other.hasUseIcon()) {
          setUseIcon(other.getUseIcon());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Net.Protol.common.Common.client_info parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Net.Protol.common.Common.client_info) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string user_name = 7 [default = ""];
      private java.lang.Object userName_ = "";
      /**
       * <code>optional string user_name = 7 [default = ""];</code>
       *
       * <pre>
       *用户相关///////////////////////////////
       * </pre>
       */
      public boolean hasUserName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string user_name = 7 [default = ""];</code>
       *
       * <pre>
       *用户相关///////////////////////////////
       * </pre>
       */
      public java.lang.String getUserName() {
        java.lang.Object ref = userName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          userName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string user_name = 7 [default = ""];</code>
       *
       * <pre>
       *用户相关///////////////////////////////
       * </pre>
       */
      public com.google.protobuf.ByteString
          getUserNameBytes() {
        java.lang.Object ref = userName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string user_name = 7 [default = ""];</code>
       *
       * <pre>
       *用户相关///////////////////////////////
       * </pre>
       */
      public Builder setUserName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        userName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string user_name = 7 [default = ""];</code>
       *
       * <pre>
       *用户相关///////////////////////////////
       * </pre>
       */
      public Builder clearUserName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userName_ = getDefaultInstance().getUserName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string user_name = 7 [default = ""];</code>
       *
       * <pre>
       *用户相关///////////////////////////////
       * </pre>
       */
      public Builder setUserNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        userName_ = value;
        onChanged();
        return this;
      }

      // optional int32 use_icon = 8 [default = 0];
      private int useIcon_ ;
      /**
       * <code>optional int32 use_icon = 8 [default = 0];</code>
       *
       * <pre>
       *正在使用的头像
       * </pre>
       */
      public boolean hasUseIcon() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 use_icon = 8 [default = 0];</code>
       *
       * <pre>
       *正在使用的头像
       * </pre>
       */
      public int getUseIcon() {
        return useIcon_;
      }
      /**
       * <code>optional int32 use_icon = 8 [default = 0];</code>
       *
       * <pre>
       *正在使用的头像
       * </pre>
       */
      public Builder setUseIcon(int value) {
        bitField0_ |= 0x00000002;
        useIcon_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 use_icon = 8 [default = 0];</code>
       *
       * <pre>
       *正在使用的头像
       * </pre>
       */
      public Builder clearUseIcon() {
        bitField0_ = (bitField0_ & ~0x00000002);
        useIcon_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Net.Protol.common.client_info)
    }

    static {
      defaultInstance = new client_info(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Net.Protol.common.client_info)
  }

  public interface match_playerOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 uid = 1 [default = 0];
    /**
     * <code>optional int32 uid = 1 [default = 0];</code>
     */
    boolean hasUid();
    /**
     * <code>optional int32 uid = 1 [default = 0];</code>
     */
    int getUid();

    // optional string name = 2 [default = ""];
    /**
     * <code>optional string name = 2 [default = ""];</code>
     */
    boolean hasName();
    /**
     * <code>optional string name = 2 [default = ""];</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 2 [default = ""];</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    // optional int32 country = 3 [default = 0];
    /**
     * <code>optional int32 country = 3 [default = 0];</code>
     */
    boolean hasCountry();
    /**
     * <code>optional int32 country = 3 [default = 0];</code>
     */
    int getCountry();

    // optional int32 icon = 4 [default = 0];
    /**
     * <code>optional int32 icon = 4 [default = 0];</code>
     */
    boolean hasIcon();
    /**
     * <code>optional int32 icon = 4 [default = 0];</code>
     */
    int getIcon();

    // optional int32 race = 5 [default = 0];
    /**
     * <code>optional int32 race = 5 [default = 0];</code>
     */
    boolean hasRace();
    /**
     * <code>optional int32 race = 5 [default = 0];</code>
     */
    int getRace();

    // optional int32 race_level = 6 [default = 0];
    /**
     * <code>optional int32 race_level = 6 [default = 0];</code>
     */
    boolean hasRaceLevel();
    /**
     * <code>optional int32 race_level = 6 [default = 0];</code>
     */
    int getRaceLevel();
  }
  /**
   * Protobuf type {@code Net.Protol.common.match_player}
   */
  public static final class match_player extends
      com.google.protobuf.GeneratedMessage
      implements match_playerOrBuilder {
    // Use match_player.newBuilder() to construct.
    private match_player(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private match_player(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final match_player defaultInstance;
    public static match_player getDefaultInstance() {
      return defaultInstance;
    }

    public match_player getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private match_player(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              uid_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              name_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              country_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              icon_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              race_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              raceLevel_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Net.Protol.common.Common.internal_static_Net_Protol_common_match_player_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Net.Protol.common.Common.internal_static_Net_Protol_common_match_player_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Net.Protol.common.Common.match_player.class, Net.Protol.common.Common.match_player.Builder.class);
    }

    public static com.google.protobuf.Parser<match_player> PARSER =
        new com.google.protobuf.AbstractParser<match_player>() {
      public match_player parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new match_player(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<match_player> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 uid = 1 [default = 0];
    public static final int UID_FIELD_NUMBER = 1;
    private int uid_;
    /**
     * <code>optional int32 uid = 1 [default = 0];</code>
     */
    public boolean hasUid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 uid = 1 [default = 0];</code>
     */
    public int getUid() {
      return uid_;
    }

    // optional string name = 2 [default = ""];
    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.Object name_;
    /**
     * <code>optional string name = 2 [default = ""];</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string name = 2 [default = ""];</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 2 [default = ""];</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 country = 3 [default = 0];
    public static final int COUNTRY_FIELD_NUMBER = 3;
    private int country_;
    /**
     * <code>optional int32 country = 3 [default = 0];</code>
     */
    public boolean hasCountry() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 country = 3 [default = 0];</code>
     */
    public int getCountry() {
      return country_;
    }

    // optional int32 icon = 4 [default = 0];
    public static final int ICON_FIELD_NUMBER = 4;
    private int icon_;
    /**
     * <code>optional int32 icon = 4 [default = 0];</code>
     */
    public boolean hasIcon() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 icon = 4 [default = 0];</code>
     */
    public int getIcon() {
      return icon_;
    }

    // optional int32 race = 5 [default = 0];
    public static final int RACE_FIELD_NUMBER = 5;
    private int race_;
    /**
     * <code>optional int32 race = 5 [default = 0];</code>
     */
    public boolean hasRace() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int32 race = 5 [default = 0];</code>
     */
    public int getRace() {
      return race_;
    }

    // optional int32 race_level = 6 [default = 0];
    public static final int RACE_LEVEL_FIELD_NUMBER = 6;
    private int raceLevel_;
    /**
     * <code>optional int32 race_level = 6 [default = 0];</code>
     */
    public boolean hasRaceLevel() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional int32 race_level = 6 [default = 0];</code>
     */
    public int getRaceLevel() {
      return raceLevel_;
    }

    private void initFields() {
      uid_ = 0;
      name_ = "";
      country_ = 0;
      icon_ = 0;
      race_ = 0;
      raceLevel_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, uid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, country_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, icon_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, race_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, raceLevel_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, uid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, country_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, icon_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, race_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, raceLevel_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Net.Protol.common.Common.match_player parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Net.Protol.common.Common.match_player parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Net.Protol.common.Common.match_player parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Net.Protol.common.Common.match_player parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Net.Protol.common.Common.match_player parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Net.Protol.common.Common.match_player parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Net.Protol.common.Common.match_player parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Net.Protol.common.Common.match_player parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Net.Protol.common.Common.match_player parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Net.Protol.common.Common.match_player parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Net.Protol.common.Common.match_player prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Net.Protol.common.match_player}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements Net.Protol.common.Common.match_playerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Net.Protol.common.Common.internal_static_Net_Protol_common_match_player_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Net.Protol.common.Common.internal_static_Net_Protol_common_match_player_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Net.Protol.common.Common.match_player.class, Net.Protol.common.Common.match_player.Builder.class);
      }

      // Construct using Net.Protol.common.Common.match_player.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        uid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        country_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        icon_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        race_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        raceLevel_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Net.Protol.common.Common.internal_static_Net_Protol_common_match_player_descriptor;
      }

      public Net.Protol.common.Common.match_player getDefaultInstanceForType() {
        return Net.Protol.common.Common.match_player.getDefaultInstance();
      }

      public Net.Protol.common.Common.match_player build() {
        Net.Protol.common.Common.match_player result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Net.Protol.common.Common.match_player buildPartial() {
        Net.Protol.common.Common.match_player result = new Net.Protol.common.Common.match_player(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.uid_ = uid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.country_ = country_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.icon_ = icon_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.race_ = race_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.raceLevel_ = raceLevel_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Net.Protol.common.Common.match_player) {
          return mergeFrom((Net.Protol.common.Common.match_player)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Net.Protol.common.Common.match_player other) {
        if (other == Net.Protol.common.Common.match_player.getDefaultInstance()) return this;
        if (other.hasUid()) {
          setUid(other.getUid());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasCountry()) {
          setCountry(other.getCountry());
        }
        if (other.hasIcon()) {
          setIcon(other.getIcon());
        }
        if (other.hasRace()) {
          setRace(other.getRace());
        }
        if (other.hasRaceLevel()) {
          setRaceLevel(other.getRaceLevel());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Net.Protol.common.Common.match_player parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Net.Protol.common.Common.match_player) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 uid = 1 [default = 0];
      private int uid_ ;
      /**
       * <code>optional int32 uid = 1 [default = 0];</code>
       */
      public boolean hasUid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 uid = 1 [default = 0];</code>
       */
      public int getUid() {
        return uid_;
      }
      /**
       * <code>optional int32 uid = 1 [default = 0];</code>
       */
      public Builder setUid(int value) {
        bitField0_ |= 0x00000001;
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 uid = 1 [default = 0];</code>
       */
      public Builder clearUid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        uid_ = 0;
        onChanged();
        return this;
      }

      // optional string name = 2 [default = ""];
      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 2 [default = ""];</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string name = 2 [default = ""];</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 2 [default = ""];</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 2 [default = ""];</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2 [default = ""];</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2 [default = ""];</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }

      // optional int32 country = 3 [default = 0];
      private int country_ ;
      /**
       * <code>optional int32 country = 3 [default = 0];</code>
       */
      public boolean hasCountry() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 country = 3 [default = 0];</code>
       */
      public int getCountry() {
        return country_;
      }
      /**
       * <code>optional int32 country = 3 [default = 0];</code>
       */
      public Builder setCountry(int value) {
        bitField0_ |= 0x00000004;
        country_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 country = 3 [default = 0];</code>
       */
      public Builder clearCountry() {
        bitField0_ = (bitField0_ & ~0x00000004);
        country_ = 0;
        onChanged();
        return this;
      }

      // optional int32 icon = 4 [default = 0];
      private int icon_ ;
      /**
       * <code>optional int32 icon = 4 [default = 0];</code>
       */
      public boolean hasIcon() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 icon = 4 [default = 0];</code>
       */
      public int getIcon() {
        return icon_;
      }
      /**
       * <code>optional int32 icon = 4 [default = 0];</code>
       */
      public Builder setIcon(int value) {
        bitField0_ |= 0x00000008;
        icon_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 icon = 4 [default = 0];</code>
       */
      public Builder clearIcon() {
        bitField0_ = (bitField0_ & ~0x00000008);
        icon_ = 0;
        onChanged();
        return this;
      }

      // optional int32 race = 5 [default = 0];
      private int race_ ;
      /**
       * <code>optional int32 race = 5 [default = 0];</code>
       */
      public boolean hasRace() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 race = 5 [default = 0];</code>
       */
      public int getRace() {
        return race_;
      }
      /**
       * <code>optional int32 race = 5 [default = 0];</code>
       */
      public Builder setRace(int value) {
        bitField0_ |= 0x00000010;
        race_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 race = 5 [default = 0];</code>
       */
      public Builder clearRace() {
        bitField0_ = (bitField0_ & ~0x00000010);
        race_ = 0;
        onChanged();
        return this;
      }

      // optional int32 race_level = 6 [default = 0];
      private int raceLevel_ ;
      /**
       * <code>optional int32 race_level = 6 [default = 0];</code>
       */
      public boolean hasRaceLevel() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional int32 race_level = 6 [default = 0];</code>
       */
      public int getRaceLevel() {
        return raceLevel_;
      }
      /**
       * <code>optional int32 race_level = 6 [default = 0];</code>
       */
      public Builder setRaceLevel(int value) {
        bitField0_ |= 0x00000020;
        raceLevel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 race_level = 6 [default = 0];</code>
       */
      public Builder clearRaceLevel() {
        bitField0_ = (bitField0_ & ~0x00000020);
        raceLevel_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Net.Protol.common.match_player)
    }

    static {
      defaultInstance = new match_player(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Net.Protol.common.match_player)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Net_Protol_common_test4_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Net_Protol_common_test4_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Net_Protol_common_test3_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Net_Protol_common_test3_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Net_Protol_common_client_info_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Net_Protol_common_client_info_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Net_Protol_common_match_player_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Net_Protol_common_match_player_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014common.proto\022\021Net.Protol.common\"A\n\005tes" +
      "t4\022\014\n\001f\030\001 \001(\005:\0010\022\026\n\003ccc\030\002 \001(\t:\tasdasdasd" +
      "\022\022\n\010cmd_data\030\003 \001(\t:\000\";\n\005test3\022\014\n\001d\030\001 \001(\005" +
      ":\0010\022$\n\002cc\030\002 \001(\0132\030.Net.Protol.common.test" +
      "4\"7\n\013client_info\022\023\n\tuser_name\030\007 \001(\t:\000\022\023\n" +
      "\010use_icon\030\010 \001(\005:\0010\"{\n\014match_player\022\016\n\003ui" +
      "d\030\001 \001(\005:\0010\022\016\n\004name\030\002 \001(\t:\000\022\022\n\007country\030\003 " +
      "\001(\005:\0010\022\017\n\004icon\030\004 \001(\005:\0010\022\017\n\004race\030\005 \001(\005:\0010" +
      "\022\025\n\nrace_level\030\006 \001(\005:\0010"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Net_Protol_common_test4_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Net_Protol_common_test4_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Net_Protol_common_test4_descriptor,
              new java.lang.String[] { "F", "Ccc", "CmdData", });
          internal_static_Net_Protol_common_test3_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_Net_Protol_common_test3_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Net_Protol_common_test3_descriptor,
              new java.lang.String[] { "D", "Cc", });
          internal_static_Net_Protol_common_client_info_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_Net_Protol_common_client_info_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Net_Protol_common_client_info_descriptor,
              new java.lang.String[] { "UserName", "UseIcon", });
          internal_static_Net_Protol_common_match_player_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_Net_Protol_common_match_player_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Net_Protol_common_match_player_descriptor,
              new java.lang.String[] { "Uid", "Name", "Country", "Icon", "Race", "RaceLevel", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
